services:
  pms-api:
    image: 353488928095.dkr.ecr.ap-northeast-2.amazonaws.com/pms:latest
    container_name: pms-api
    ports:
      - "8000:8000"
    environment:
      APP_ENV: production
      PMS_DATABASE_URL: ${PMS_DATABASE_URL}
      PMS_WEBHOOK_TOKEN: ${PMS_WEBHOOK_TOKEN}
      CARPAYIN_BACKEND_BASE_URL: http://internal-hd-internal-alb-998881429.ap-northeast-2.elb.amazonaws.com:8000
      PMS_FEE_PER_30_MINUTES: "500"
      PMS_REDIS_URL: redis://mockpms-redis.vkjvvb.ng.0001.apn2.cache.amazonaws.com:6379/0
      BARRIER_ENABLED: "true"
      BARRIER_ENTRY_URL: ${BARRIER_ENTRY_URL}
      BARRIER_EXIT_URL: ${BARRIER_EXIT_URL}
    restart: unless-stopped
