apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mock-card-secret
  namespace: mock-card
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: SecretStore
  target:
    name: mock-card-env
    creationPolicy: Owner
  data:
    - secretKey: MOCK_CARD_DATABASE_URL
      remoteRef:
        key: mock-card
        property: database_url
    - secretKey: MOCK_CARD_SECURITY_SECRET
      remoteRef:
        key: mock-card
        property: security_secret