apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: mock-card
spec:
  provider:
    vault:
      server: "http://10.0.3.241:8200"
      path: "secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "placeholder"
          secretRef:
            name: vault-approle
            key: secret-id